version: '3.8'

services:
  app:
    image: docker.io/peterroe/ogimg:latest
    ports:
      - "8888:8888"
    environment:
      - APP_CONF=./config/prod.yml
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    volumes:
      - ./config/:/app/config/   

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
