version: '3.8'

services:
  app:
    image: peterroe/ogimg:latest
    ports:
      - "8888:8888"
    environment:
      - APP_CONF=./config/prod.yml
    depends_on:
      - og-redis
    volumes:
      - ./config/:/app/config/

  og-redis:
    image: "redis:alpine"
