version: '3.8'

services:
  app:
    build: .
    ports:
      - "8888:8888"
    environment:
      - APP_CONF=./config/local.yml
    depends_on:
      - og-redis
    volumes:
      - ./config/:/app/config/

  og-redis:
    image: redis:alpine
